id: bring_your_own_data_chat_qna
name: Bring Your Own Data Chat QnA
inputs:
  chat_history:
    type: list
    default:
    - inputs:
        chat_input: Hi
      outputs:
        chat_output: Hello! How can I assist you today?
    - inputs:
        chat_input: What is Azure compute instance?
      outputs:
        chat_output: An Azure Machine Learning compute instance is a fully managed
          cloud-based workstation for data scientists. It provides a
          pre-configured and managed development environment in the cloud for
          machine learning. Compute instances can also be used as a compute
          target for training and inferencing for development and testing
          purposes. They have a job queue, run jobs securely in a virtual
          network environment, and can run multiple small jobs in parallel.
          Additionally, compute instances support single-node multi-GPU
          distributed training jobs.
    is_chat_input: false
    is_chat_history: true
  chat_input:
    type: string
    default: How can I create one using azureml sdk V2?
    is_chat_input: true
outputs:
  chat_output:
    type: string
    reference: ${chat_with_context.output}
    is_chat_output: true
nodes:
- name: modify_query_with_history
  use_variants: true
- name: lookup
  type: python
  source:
    type: package
    tool: promptflow_vectordb.tool.common_index_lookup.search
  inputs:
    mlindex_content: >
      embeddings:
        api_base: https://webassistantazureopenai.openai.azure.com
        api_type: Azure
        api_version: 2023-07-01-preview
        batch_size: '16'
        connection:
          id: 
            /subscriptions/f70d1881-a5f2-4c8c-8344-3e1ffde707fd/resourceGroups/RG-project-Assistant/providers/Microsoft.MachineLearningServices/workspaces/raft-assistant/connections/webassistantazureopenai
        connection_type: workspace_connection
        deployment: text-embedding-ada-002
        dimension: 1536
        file_format_version: '2'
        kind: open_ai
        model: text-embedding-ada-002
        schema_version: '2'
      index:
        api_version: 2023-07-01-preview
        connection:
          id: 
            /subscriptions/f70d1881-a5f2-4c8c-8344-3e1ffde707fd/resourceGroups/RG-project-Assistant/providers/Microsoft.MachineLearningServices/workspaces/raft-assistant/connections/websitesearchserviceinstance
        connection_type: workspace_connection
        endpoint: https://website-search-service-instance.search.windows.net/
        engine: azure-sdk
        field_mapping:
          content: content
          embedding: contentVector
          filename: filepath
          metadata: meta_json_string
          title: title
          url: url
        index: webindex
        kind: acs
        semantic_configuration_name: azureml-default
      self:
        path: 
          azureml://subscriptions/f70d1881-a5f2-4c8c-8344-3e1ffde707fd/resourcegroups/rg-project-assistant/workspaces/raft-assistant/datastores/workspaceblobstore/paths/azureml/3960b6cd-6188-461a-816e-0e8ad100af8d/index/
        asset_id: 
          azureml://locations/swedencentral/workspaces/f1499daf-1c6b-4c3d-94b8-88f486312c90/data/webindex/versions/1
    queries: ${modify_query_with_history.output}
    query_type: Hybrid (vector + keyword)
    top_k: 2
  use_variants: false
- name: generate_prompt_context
  type: python
  source:
    type: code
    path: generate_prompt_context.py
  inputs:
    search_result: ${lookup.output}
  use_variants: false
- name: Prompt_variants
  type: prompt
  source:
    type: code
    path: Prompt_variants.jinja2
  inputs:
    contexts: ${generate_prompt_context.output}
    chat_history: ${inputs.chat_history}
    chat_input: ${inputs.chat_input}
  use_variants: false
- name: chat_with_context
  type: llm
  source:
    type: code
    path: chat_with_context.jinja2
  inputs:
    deployment_name: Raft-Assistant-gpt-4-0613
    temperature: 0
    top_p: 1
    max_tokens: 1000
    presence_penalty: 0
    frequency_penalty: 0
    prompt_text: ${Prompt_variants.output}
  provider: AzureOpenAI
  connection: webassistantazureopenai
  api: chat
  module: promptflow.tools.aoai
  use_variants: false
node_variants:
  modify_query_with_history:
    default_variant_id: variant_0
    variants:
      variant_0:
        node:
          name: modify_query_with_history
          type: llm
          source:
            type: code
            path: modify_query_with_history.jinja2
          inputs:
            deployment_name: Raft-Assistant-gpt-4-0613
            temperature: 0
            top_p: 1
            max_tokens: 1000
            presence_penalty: 0
            frequency_penalty: 0
            chat_history: ${inputs.chat_history}
            chat_input: ${inputs.chat_input}
          provider: AzureOpenAI
          connection: webassistantazureopenai
          api: chat
          module: promptflow.tools.aoai
      variant_1:
        node:
          name: modify_query_with_history
          type: llm
          source:
            type: code
            path: modify_query_with_history__variant_1.jinja2
          inputs:
            deployment_name: Raft-Assistant-gpt-4-0613
            temperature: 0
            top_p: 1
            max_tokens: 1000
            presence_penalty: 0
            frequency_penalty: 0
            chat_history: ${inputs.chat_history}
            chat_input: ${inputs.chat_input}
          provider: AzureOpenAI
          connection: webassistantazureopenai
          api: chat
          module: promptflow.tools.aoai
environment:
  python_requirements_txt: requirements.txt
